#+title: 范数
#+roam_tags: 泛函分析
#+roam_alias: 赋范空间 模

* 定义
范数通过它的性质定义。在[[file:20201016153155-线性空间.org][线性空间]] \(\mathbb{X} \) 上，满足以下条件的实值函数称为范数 \(p(\cdot):\mathbb{X}  \to \mathbb{R} \) 。
- 非负，且范数为零 \(\iff\) 元素为零。
- 被数乘的元素的范数等于元素的范数的数乘 \(p(\alpha x) = |\alpha| p(x)\) 。
- 三角不等式 \(p(x+y)\leq p(x)+p(y)\) 。

简写为 \(\lVert \cdot \rVert\) 。

有范数的 *线性空间* ，或赋了范数的空间，称为赋范空间。

* 例子
- \(\mathbb{X} :=\mathbb{C} \) 时，若设 \(\lVert u \rVert = |u|\) ，那么 \(\mathbb{X} \) 就是复赋范线性空间了。

-----

- 范数是实数域绝对值概念的一般化。是 *长度* 概念在泛函分析里的体现。范数将[[file:20201016153155-线性空间.org][线性空间]]中的每一个元素都对应了一个实数。

- 我们可以使用范数来定义收敛。
  通过 \(\lim\limits_{n\to\infty}\lVert u_n - u \rVert = 0\)，我们可以定义收敛。（当然，需要在[[file:20201016153155-线性空间.org][线性空间]]中才有减法）

- 范数 \(\lVert u-v\rVert\) 可以称为元素 \(u,v\) 的[[file:20200930133725-距离空间.org][距离]]；如果 \(v=0\) ，那么 \(\lVert u \rVert\) 就是 \(u\) 点到原点 \(v=0\) 的距离。

- 关于赋范空间和距离空间的区别，参见[[file:20201018191324-比较赋范空间和距离空间.org][比较赋范空间和距离空间]]。
  既然赋范空间选定一定的距离就可以成为距离空间， 那么距离空间上的一切性质它都可具备，比如[[file:20201007122858-距离空间的临域.org][临域]]、[[file:20201007124012-开集.org][开集]]、[[file:20201009222152-闭集.org][闭集]]、[[file:20201006213407-距离空间的序列收敛_极限.org][收敛]]、[[file:20201007144711-基本列.org][基本列]]、[[file:20201007143747-距离空间的完备性.org][完备性]]、[[file:20201007142134-可分性.org][可分性]]、[[file:20201007153150-列紧性.org][紧性]]
