#+title: 列紧集和列紧空间
#+roam_tags: 泛函分析
#+roam_alias:

实数域的完备带来了一个性质： *每一个有界无限集至少有一个聚点* ，这就是实数域中有界无限集的列紧性。
我们将这个性质推广到完备距离空间，探讨列紧性成立的条件。

* 定义
- 列紧集 :: 距离空间子集 \(A \subseteq X\) 中的任何点列 \(\{x_n\}\) 都存在 *子列* \(\{x_{n_k}\}\) 使得 \(x_{n_k} \to x \in X\) ，那么称 \(A\) 为列（准）紧集。
  + 即 \(A\) 中的任何序列的子列都一定收敛于 \(X\) 内的一点。
- 列紧空间 :: 如果距离空间 \(X\) 是列紧集，则称之为列紧空间。
* 性质和关系
- 列紧闭集称为[[file:20201205204426-自列紧集.org][自列紧集]]。
- 距离空间中的列紧集是[[file:20201205190624-距离空间的有界性.org][有界集]]，反之不成立
- 列紧集的子集也是列紧集
  + 按定义，列紧集的任意点列都存在收敛子列，那么列紧集子集中的任意点列（和原集合中是同一点列？）也存在收敛子列。
- \(A \subseteq X\) 列紧 \(\iff\) \(\overline{A} \) 自列紧，[[file:20201205214035-证明_列紧集的闭包是自列紧集.org][证明]]
- [[file:20201205225256-证明_列紧空间是完备的.org][列紧空间是完备的]]。因而自列紧集作为子空间也是完备的。
** 列紧空间和列紧集的例子
自然数空间 \(N\) 不是列紧空间，因为点列 \(\{n\}(n=1,2, \dots)\) 不存在任何收敛子列
实数空间 \(R\) 是列紧空间，开区间 \((a,b)\) 是 \(R\) 中的列紧集，闭区间 \([a,b]\) 是自列紧集
** 列紧集一定有界、可分
根据[[file:20201206181142-豪斯道夫定理.org][豪斯道夫定理]]，列紧集一定是[[file:20201205234048-全有界集.org][全有界集]]，而全有界集[[file:20201205190624-距离空间的有界性.org][有界]]而且[[file:20201007142134-可分性.org][可分]]，那么列紧集便也是如此。
** [[file:20201206230339-证明_集合是列紧集等价于集合存在列紧的任意epsilon网.org][集合列紧等价于集合存在列紧的任意epsilon网]]
这条定理，也可以说等价于集合存在列紧的 *在集合中稠密的* 集合。
如果有稠密的集合列紧了，那么原集合也列紧。
