#+title: 线性空间
#+roam_tags: 泛函分析 线性代数
#+roam_alias: 张成

* 粗略概括
首先粗略地说，如果定义集合 \(\mathbb{F}\) 为 *实数集或复数集* ，那么，定义在 \(\mathbb{F}\) 上面的线性空间 \(\mathbb{X}\) 就是能够构造线性组合 \(\alpha u+\beta v\) (这里 \(u,v \in \mathbb{X}; \alpha,\beta \in \mathbb{K}\))的一个集合，而且一般的线性法则（如三维向量的一般法则）都成立。

* 严格定义
严格地说（使用[[file:20201019224643-群.org][群]]和[[file:20201019232551-域.org][域]]的概念），如果
1. \(\mathbb{F} \) 是[[file:20201019232551-域.org][域]]
2. \(\mathbb{X}\) 是[[file:20201022191723-加法群.org][加法群]]
3. 用 \(\mathbb{X}\) 和 \(\mathbb{F} \) 的元素定义了纯量乘法运算，即分别从 \(\mathbb{X},\mathbb{F} \) 取任意两个元素，它们存在 \(\mathbb{X}\) 内的唯一运算结果。
4. 数乘运算满足几个公理
   a. 数 1 数乘不改变 \(\mathbb{X}\) 中的元素， \(1x = x\)
   b. 结合律，\(\alpha\beta x = \alpha(\beta x)\)
   c. 左分配率，\((\alpha+\beta)x=\alpha x +\beta x\)
   d. 右分配率，\(\alpha(x+y) = \alpha x+\alpha y\)
那么 \(\mathbb{X} \) 就称为线性空间。

上述中的数乘运算的四个公理加上群的三个定义公理加上[[file:20201019224643-群.org][交换群]]的交换律公理，可以得到定义线性空间的“八个公理”。

* 性质
- 这里的 \(\mathbb{K} \) 若是实数集，对应的线性空间是实线性空间、否则，是复线性空间。
- 如果 \(\mathbb{X} := \mathbb{F \) ，那么它可以证明也是一个线性空间。就是说，实数集、复数集是自然的线性空间。

- 如果 \(\mathbb{X} := \mathbb{F}^N\) ，也就是 N 维数集或 N 个数集的笛卡尔积，那么它也是线性空间。

- [[file:20201004142655-连续函数空间.org][连续函数空间]]也可以看作线性空间，因为对于空间中的元素 \(u,v\) ，如果我们定义加法为 \((u+v)(x) = u(x)+v(x)\) ，定义数乘为 \((\alpha u)(x) = \alpha u(x)\) ，那么得到的新元素 \(u+v, \alpha u\) 都依然是连续函数，从而还在空间之内。而且线性性质他们也满足。这个空间也是 *实线性空间* 。

- 线性空间可以由向量张成。两个或多个向量的全部线性组合构成的向量集合就是它们张成的空间。
  *例如* 两个不共线的二维向量，他们的线性组合构成所有的二维向量，这时就说它们张成的空间是所有二维向量的集合。
