#+title: 里斯引理
#+roam_tags: 泛函分析
#+roam_alias: Riesz引理

* 引入
- 赋范空间的真[[file:20201021143612-线性子空间.org][子空间]]可能是稠密的，例如多项式空间在 \(C[a,b]\) 中是稠密的，而且是真子空间
- 赋范空间 \(X\) 的 *闭子空间* \(M\) 如果稠密，就一定 *不是* 真闭子空间。就是说稠密的闭子空间和原空间相同。 *赋范空间没有真的、稠密的、闭的子空间*
  + 因为按稠密的定义， \(X \subset \overline{M} \) ，而对于闭集又有 \(M=\overline{M} \) ，那么 \(X\subset M,M\subset X\) 同时成立， \(M=X\) 。
- 上面的命题可以推出，赋范空间的 *真闭子空间一定不稠密* 。
  那么对于赋范空间 \(E\) 的真闭子空间 \(E^{0}\subsetneq E \) ，
  \(\exists x_0 \in E:x_0 \not\in E=\overline{E} \iff B(x_0,\epsilon_0)\cap E^{0} =\emptyset\) ，
  那么 \(x_0\) 和 \(E^{0} \) 之间一定 *有正的距离*
- 在 \(R^{2} \) 中，我们认为 \(x\) 和平面 \(E^{0} \) 的距离是 \(\lVert x \rVert \iff x \perp E^{0} \) ，而且一定存在一个点和 \(E^{0} \) 有正距离。但这需要正交概念的存在。
- 在没有正交概念的 *巴拿赫空间* 中是否也有某个点 \(x\) 和真闭子空间 \(E^{0} \) 的距离是 \(\lVert x \rVert \) ？
- 我们仅考察空间中的单位球 \(\lVert x \rVert =1\) ，那么问题就变成：单位球上是否有某个点和 \(E^{0} \) 的距离是1？
  + 仅考察单位球相当于考察了空间所有点，因为线性空间的 *数乘性质* ，单位球的性质可以 *推广到全空间* 。
- *里斯引理* 试图回答这个问题：虽然在一般的巴拿赫空间中无法肯定找到距离是1的点，但是 *距离比1小一点的点* 是肯定可以找到的。可以找到那些在单位球上距离接近1的点。
* 定义
对于赋范线性空间 \(E\) 的真闭子空间 \(E^{0}\subsetneq E \) ：
\(\forall \epsilon >0:\exists x \in E:\lVert x \rVert =1:\forall x_0 \in E^{0} :\inf_{x^{ 0 } \in E^{ 0 } }\lVert x^{ 0 } -x \rVert \geq 1-\epsilon\)
* 性质或关系
条件 \(> 1-\epsilon\) 一般不能加强为 \(\geq 1\) ，距离不能保证取到1（泛函分析中的反例 p40 ）
*子空间是闭集，是必要条件* 。假设子空间不是闭集，那么子空间之外的点不能保证 *到子空间有正的距离* 。距离假若等于零是无法推出里斯引理的。
* Footnotes
