#+title: 距离空间的完备性
#+roam_tags: 泛函分析
#+roam_alias: 完备距离空间

* 定义
如果[[file:20200930133725-距离空间.org][距离空间]] \(\mathbb{X}\) 中的每个[[file:20201007144711-基本列.org][基本列]]都[[file:20201006213407-按距离收敛和极限.org][收敛]]，那么 \(\mathbb{X}\) 称为完备距离空间。
* 性质和关系[fn:1]
** 完备性和闭集的概念来自数学分析中实数系的完备性和闭集。
作用也类似：为后续研究提供严谨的理论基础。
** 可以证明：距离空间中任何[[file:20201006213407-按距离收敛和极限.org][收敛点列]]都是基本列。
那么对完备的距离空间，按照定义下列命题成立：
\(\forall \{x_n\} \subset \mathbb{X}, \{x_n\}\) 收敛 \(\iff\) \(\{x_n\}\) 是基本列
** 闭球套定理
- 距离空间完备 \(\iff\) 距离空间中存在 *交于唯一一点* 的半径趋于 0 的[[file:20201021114102-闭球套.org][闭球套]]。 \(\iff\) 闭球套定理成立。
** 空间是完备距离空间等价于空间的闭子空间完备
- 求证：完备空间 \(X\) 的任何闭[[file:20201204193523-距离子空间.org][子空间]] \(F\) 都是完备的。
- 证明思路：在子空间中取一基本列 \(\{x_n\} \subset F\subset X\) ，由于 \(X\) 完备，所以基本列收敛于 \(X\) ，又因为 \(F\) 是[[file:20201009222152-闭集.org][闭集]]，闭集内点列的极限点一定在闭集之中，所以 \(x_n \to x \in F\) ，任意基本列收敛，即证。
** 距离空间完备子空间是闭集
求证：若 \(X\) 的子空间 \(F\) 按照 \(X\) 的距离是完备的，那么 \(F\) 是闭集。
证明思路：任取基本列 \(\{x_n\} \subset F \subset X\) ，由于 \(F\) 完备， \(x_n\to x \in F\) ，所以 \(F\) 对极限运算封闭，是闭集。

如果把完备距离空间本身看作自己的子空间，那么可以推出 *完备距离空间是闭集*.
** 定理：任一完备距离空间均为[[file:20201021131759-第一范畴集和第二范畴集.org][第二类型的集]]。
** 完备的意思是空间没有（极限意义上的）空隙，让极限不因空间漏洞而不存在
完备性定义为所有基本列收敛，这是什么意思呢？
我们可以将完备理解为：空间没有（极限意义上的） *漏洞或空隙*

*不完备的，有空隙的距离空间* 比如 \(\left(Q,d(x,y)=|x-y|\right)\) 有理数空间。
一个由有理数构成的数列是有可能收敛到无理数的，比如 \(\left( 1+ \frac{1}{n} \right)^{1/n} \to e\) 。
而在有理数空间中这个数列无法收敛，因为 \(e\) 不存在，虽然这个数列是 *基本列* 。

基本列就是 *两个项之间的距离可以任意小的序列* ，而在不完备的空间中，一部分基本列
- *无法收敛到空间中的任何元素* ，或者说
- *序列项和空间中任何一个元素的距离都无法任意小* 。

另外，如果空间中存在一个可以和序列项的距离达到任意小的元素，这个元素也 *只能有一个* 。（[[file:20201125152908-收敛序列的极限唯一性证明.org][极限的唯一性]]）

完备的空间不会因为空间中的漏洞而发生柯西列不收敛的情况。
** 每个距离空间都可以完备化
每个距离空间都有自己的[[file:20201204111453-完备化空间.org][完备化空间]]。
** 完备距离空间例子
- \(\mathbb{R} ^n\) 按照通常距离是完备的
- [[file:20201004142655-连续函数空间.org][连续函数空间]]按照 \(\max|\cdot|\) 距离是完备的。
- [[file:20201007105119-l_p_e_空间.org][l^p(E)空间]]按距离 \(\int_{[a,b]}|\cdot|^p dm\) 是完备的。
- [[file:20201007115530-l_p空间.org][l^p空间]]按距离 \((\sum_{i=1}^\infty |\cdot|^{p} )^{\frac{1}{p}} \) 是完备的。

* Footnotes

[fn:1] [[file:~/org_notebooks/journal/20201204::*距离空间的完备性和闭集][距离空间的完备性和闭集]]
