#+title: 点目标雷达方程的推导
#+roam_tags: 
#+roam_alias: 

* 主要内容
雷达测距方程（radar range equation）表示发射功率和到接收到反射回波为止的波传播之间的物理依赖关系（ dependencies ）。
- \(P_e\) 返回到接收天线的功率
- \(P_S\) 传输功率
- \(R\) 距离
- \(\sigma\) 描述目标反射特性的雷达截面

假定电磁波在理想条件下传播，就是没有色散。
各向同性辐射子辐射的高频能量在各方向均匀分布，那么以辐射子为中心的任意球面上的功率密度都相同，这就是无方向性功率密度（non-directional power density）：
\[S_u = \frac{P_s}{4\pi R_1^2 }\]
\(R_1\) 是发射天线到目标的距离。

如果天线的能量不是在全方向均匀辐射，而是在某个方向有更多辐射，那么辐射的 *功率重新分配* 以使得该方向的辐射功率密度 *放大* ，这种效应定义为天线 *增益*  \(G\) ，从而我们也能定义有方向性功率密度（directional power density）就是无方向性功率密度和增益的乘积：
\[S_g = S_u G = \frac{P_s}{4\pi R_1^2 }G\] 
这个式子是先定义了增益，然后用增益定义了 \(S_g\) 。也可以反过来定义：先定义 \(S_g\) ，然后定义增益是 \({S_g} / {S_u}\) 。

#+begin_note
[[file:20210401231356-雷达增益.org][增益]]就是指 *有方向性天线相对于无方向性天线，在某个方向上功率增加的倍数* 。这个倍数可能大于 1 [主瓣方向]，也可能小于 1 [副瓣方向]。从能量守恒的角度来讲，主瓣获得的功率增益，是以牺牲副瓣增益得到的。
#+end_note

目标探测不止取决于目标位置的功率密度，还取决于 *在雷达系统的方向上* 被目标实际反射的功率份数。
为了确定能用的反射功率，需要引入雷达截面 \(\sigma\) 的概念。
它取决于几个因素，其中有面积因素，面积越大反射越多，就是说同种飞行情况下，空中巴士的雷达截面比私人飞机的大。除此之外还有设计因素、表面成分、材料因素。

总结上文， *目标处的* 反射功率 \(P_r\) 取决于无方向性功率密度 \(S_u\) 、天线增益 \(G\) 和雷达截面 \(\sigma\) ：
\[P_r = S_g \sigma = \frac{P_s}{4\pi R_1^2 }G\sigma\]

这可以看作雷达截面的定义，也就是反射功率和有方向性（发射）功率密度的比率。

目标会发出反射功率，被接收天线接收到，这就如同发射天线发出发射功率被目标接收到一样，所以我们也可以把目标看作一个辐射子，那么反射功率就也是一种发射功率了。那么我们可以向定义无方向性功率密度一样定义接收功率密度：
\[S_e = \frac{P_r}{4\pi R_2^2 }\] 
\(R_2\) 是目标到接收天线的距离。

雷达接收天线处的接收功率就是接收功率密度和有效天线面积 \(A_w\) 的乘积：
\[P_e = S_e A_w\]
其中 \(A_w = A K_a\) ，\(A\) 就是天线面积，\(K_a\) 是其中有效部分的比率。

* 参考
- https://www.tutorialspoint.com/radar_systems/radar_systems_range_equation.htm
- https://www.radartutorial.eu/01.basics/The%20Radar%20Range%20Equation.en.html
- https://zhuanlan.zhihu.com/p/150601023
- 关于增益：
- https://zhuanlan.zhihu.com/p/149757466
