#+title: 使用快速傅立叶变换仿真衍射光学的二维抽样理论
#+roam_tags: 
#+roam_alias: 

* 概括
* 由comb函数确定的抽样间隔和频谱岛间隔之间的倒数关系
抽样这件事，可以使用comb函数和被抽样函数的乘积表示。comb就是均匀排列的delta函数。

comb函数的傅立叶变换，或者说频谱也是comb函数。

comb函数有一个性质，它的delta函数之间的间隔和它的频谱中的delta函数之间的间隔，是倒数的关系。

根据卷积定理，乘积的傅立叶变换是卷积。那么comb函数和被抽样函数的乘积，其频谱就是另一个comb函数和被抽样函数频谱的卷积。而comb函数无非是均匀排列的delta函数，那么乘积的频谱就应该是均匀排列的被抽样函数的频谱。我们称之为 *频谱岛* 。

频谱岛之间的间隔，也就是时域的comb函数中的delta函数的间隔的 *倒数* 。

这就意味着，时域抽样间距越小，频谱岛间隔越大。

考虑一个特例：没有抽样的连续函数，它也可以看作抽样间隔无穷小，那么频谱岛间隔就是无穷大。所以我们只能看到它的一个频谱。

* 引入衍射光学，以及圆形频谱遇到矩形抽样的欠抽样时会发生什么？
对于衍射的模型，时域和频域是什么？时域是衍射面，频域是观察屏。那么正如上面的分析，在这里也会出现观察屏上的频谱岛，也就是分立的观察屏上的衍射场。而且频谱岛间隔是抽样间隔的倒数。如果抽样间隔太大，频谱岛之间就会离得很近，从而发生混叠。

由于我们的抽样不是极坐标系下的抽样，而是在笛卡尔直角坐标系的抽样，或者说comb函数是x,y的函数，而不是 \(\rho,\theta \) 的函数，所以它的每个delta函数会在排列矩形网格上。相应地，各个频谱岛也是排列在矩形网格上的。

如果我们的频谱是一个圆对称的函数，而且发生了频谱混叠时会发生什么呢？由于抽样本身的矩形特征，或者comb函数的矩形特征，原本应该是圆对称的频谱，就会呈现出矩形特征。

在运用这些算法之前，都需要进行抽样，如何抽样能够避免图像出现欠抽样的现象，是一个复杂的问题。

* 关于S-FFT算法的频谱岛间隔、抽样间隔、频谱混叠、观察屏最大尺度之间的关系。
对于S-FFT算法，已知的理论结果如下。

S-FFT算法首先将衍射面光场与一个复系数相乘，然后将积进行二维傅里叶变换，所得的二维频谱与观察屏光场只不过差了一个系数。所以将二维频谱乘上相应的系数，就得到观察屏光场了。

每一对采样数和衍射面尺度对应着一个衍射面的采样间隔。
采样间隔对应着频谱的频谱岛间隔，根据comb函数的性质，频谱岛间隔就是采样间隔的倒数。

频谱岛间隔对应着一个界限，界限的两旁是频谱混叠发生和不发生，界限的值是频谱岛间隔的二分之一。一旦每个频谱岛的最大频率超过这个界限，就会发生混叠。如果每个频谱岛的最大频率都不超过这个界限，就不会发生混叠。

每个频谱岛的最大频率是由什么决定的？是由频谱函数本身的性质决定的。对于我们的例子而言，它是由函数 \(F\left\{U(x,y,0)\exp [\frac{jk}{2d}(x^2 +y^2 )]\right\}\) 的性质决定的。

根据频谱和观察屏空间的映射关系，一旦每个频谱岛的不发生混叠时的最大频率的界限确定，那么观察屏可观察（而不发生混叠）的最大尺度的界限就确定。或者说为了不发生混叠，我们需要让
* SFFT实际使用的时候抽样的限制
[[file:20210501154920-二维抽样理论.org][抽样]]的时候必须满足以下等式：
\[L = \frac{\lambda Nz}{L_0}\] 
| L   | 观察屏边长         |
| L_0 | 衍射面边长         |
| \lambda   | 波长               |
| z   | 衍射屏到观察屏距离 |

* 参考
