#+title: goodman的傅里叶光学导论习题解答的推荐习题
#+roam_tags: 
#+roam_alias: 

* 概括
goodman亲自推荐的习题，我进行了翻译。

原书是针对第三版，现在第四版的题号有所不同，我将有改动的第四版的题号放在括号中。

* 主要内容
2-4介绍了一个观念：接连两次傅里叶变换（两次的放缩因子可以不同）的结果是一张被放大或缩小的图像。

2-8（10）探究余弦对象造成余弦图像的条件，很有启发性。

2-14介绍维格纳分布，你在书中的其他地方不会遇到这个重要概念（第四版已经移到正文）

3-6单色光衍射积分如何一般化，应用于非单色窄带光

4-4（5）一个简单且让人满意的证明

4-11（13）导出衍射光栅的一个重要性质

4-12（14）介绍了一个重要而且简单的计算光栅衍射效率的方法（第四版内容删减了很多）

4-15（17）分析了一种很有趣、很重要的光栅类型

4-16（18）介绍了一种重要思想

4-18（20）可以很好的提升对自成像（self-imaging）现象的理解

第三版的第五章对应第四版的第六章，仅举一例

5-5（6-5）提升对渐晕（vignetting）现象的理解

5-6介绍像散处理机（astigmatic processor）

5-9提升对傍轴近似的理解

5-14介绍菲涅尔波带片的思想，以及它对透射波的效应

第三版的第六章对应第四版的第七章，仅举一例

6-2（7-2）介绍线扩展函数的概念，以及阶跃响应的概念

6-3图解了中心遮挡对于OTF的影响

6-7要求导出针孔相机针孔的最佳尺寸，是我个人最喜欢的

6-8非常长见识

6-15阶跃响应得更多介绍

6-17虽然很简单，但传递了重要信息

第三版的第七章对应的是第四版的第9章（波前调制），所以章节号对应的是9，但是介绍的习题全都删除了，只能参考第三版了。

7-5接触 jones calculus ，与课本中解决问题的方法略有不同

7-6介绍另一种使用磁-光（magneto-optic）空间光调制器的方法

7-7有趣而且实用的问题

第八章对应第十章。

8-1简单介绍了相干背景对于相干成像的重要性

8-5提供了典型相干光学处理系统中的实际校准要求

8-10提供了一个使用相干光和非相干光的系统，对学生是一个很好的练习

8-11对于VanderLugt滤光器（filter）的很好练习

8-15需要一些技巧，很长见识

8-16很好的练习，关于反向过滤，是另一个我最喜欢的题

第九章对应第十一章，不过第12题在第四版没有

9-5让学生练习他对全息术中成像位置和放大相关的知识

9-6关于X射线全息术的问题，很长见识

9-7虽然冗长而又复杂，但提供了一些厚全息术的波长和角灵敏度的真实数字

9-10强烈推荐

9-12值得一做，帮助理解计算机生成的全息图的采样要求

第十章对应第十二章

10-3得到一个简单而且直观上让人满意的结果，关于频谱全息术（spectral holography）中参考和信号脉冲的允许时间间隔。

10-6帮助学生理解阵列波导光栅的波长映射（wavelength mapping）性质

* 参考
[[file:~/Downloads/Introduction To Fourier Optics, Third Edition, Problem Solutions by Joseph W. Goodman (z-lib.org).pdf][goodman的傅里叶光学习题解答]]
