#+title: 标量衍射理论的推导
#+startup: num
#+roam_tags: 
#+roam_alias: 

标量衍射理论的推导过程有很多 *前提* ，这里旨在将这些前提清楚地表现出来。
* 前提：无源的麦克斯韦方程组
\begin{gather*}
\nabla\times\vec{E} = -\mu\frac{\partial\vec{H}}{\partial t}\\
\nabla\times\vec{H} = -\epsilon\frac{\partial\vec{E}}{\partial t} \\
\nabla\cdot\epsilon\vec{E} = 0 \\
\nabla\cdot\mu\vec{H} = 0
\end{gather*}
 
* 前提：介质需要满足的条件
我们仅描述无磁性、线性、各向同性、均匀、无色散介质
** 介质没有磁性
就是说 \(\mu =\mu_0\) 总是成立的。
** 介质满足线性
意义需要阐述
** 介质满足各向同性
就是说介电常数不随 *电磁波的偏振方向* 改变
\[d \epsilon / d \hat{e} = 0\]
这里 \(\hat{e} \) 表示偏振方向的单位矢量
** 介质是均匀介质
就是说介电常数不随空间位置改变。
\[d \epsilon / d \vec{r} = 0\]
** 介质是无色散介质
介电常数不随波长改变。
\[d \epsilon / d \lambda = 0\]

* 前提：矢量恒等式
矢量场旋度的旋度，等于它散度的梯度减去它的拉普拉斯
#+begin_note
拉普拉斯就是用拉普拉斯算子作用的结果，对于标量场就是梯度的散度，和散度的梯度相对应，虽然这是矢量场。

关于拉普拉斯算子的作用的探讨可见[[file:20210325110018-拉普拉斯算子的意义.org][拉普拉斯算子的意义]]。
#+end_note
\[\nabla \times (\nabla\times \vec{E}) = \nabla(\nabla\cdot \vec{E}) - \triangle \vec{E}\] 

* 前提：旋度和对时间偏导可以交换次序
\[\nabla \times \frac{\partial \vec{H} }{\partial  t}\] 中的旋度和对时间求偏导必须可以交换次序。这样才能将麦克斯韦方程组化成标量波动方程。
其前提是磁场强度关于空间坐标和时间的混合二阶偏导数都是连续的
https://zhuanlan.zhihu.com/p/161450359

* 1-4的推论：标量波动方程
由于均匀介质， \(\epsilon \) 不随空间变化，麦克斯韦方程组中的 \(\nabla \cdot \epsilon \vec{E} = \epsilon \nabla \cdot \vec{E} = 0\) ，毕竟nabla算符是对空间的偏导数组成的。
由于无磁性，\(\mu \) 也不随空间变化。
所以将麦克斯韦方程组关于电场强度的几个方程代入到矢量恒等式中，就可以得到
\[\triangle \vec{E} - \mu \epsilon \frac{\partial^2 \vec{E} }{\partial t^2 } = 0\] 
然后令 \(\mu \epsilon = n^2 / c^2 \) ，用折射率和光速代替介质的系数（转换关系略，容易查），就得到矢量波动方程
\[\triangle \vec{E} - \frac{n^2}{c^2} \frac{\partial^2 \vec{E} }{\partial t^2 } = 0\] 
容易证明，磁场强度也满足这种方程。

显然，矢量的各个分量都满足同样的方程，所以使用一个标量波动方程就足以描述场了。
\[\triangle u(P,t) - \frac{n^2}{c^2} \frac{\partial^2 u(P,t) }{\partial t^2 } = 0\] 
这个 \(u(P,t)\) 就可以描述所有分量了。
另外，\((P,t)\) 的引入意味着明确了场对空间和时间的依赖关系

* 讨论：标量波动方程的适用范围：各个矢量分量无耦合
标量波动方程能够成立需要满足很多前提，一旦某个前提受到破坏，就不再成立了。
比如说在[[file:20210326180549-电磁场边界效应.org][介质边界处]]，电场强度和磁场强度会发生耦合（就是说电场或磁场各个分量不再满足同一波动方程）
对于衍射问题，孔径处就是介质边界，它周围的空间就会发生这种耦合。
孔径越小，这种耦合效应就越小，现象就更符合标量衍射理论。
孔径小相当于衍射角小，所以衍射角的大小会对标量衍射理论的适用范围产生影响。

* 前提：单色标量波的数学形式
我们只考虑单色波，单色标量波的基本形式是
\[u(P,t) = A(P)\cos[2\pi\nu t - \phi(P)]\] 
其中的各个量的含义是显然的。

它可以使用复数表示为
\[u(P,t) = Re(U(P)\exp(-j2\pi\nu t))\] 
其中 \(U(P)=A(P)\exp [j\phi(P)]\) ，它只关于空间位置，称为相矢量。

* 5,7的推论：亥姆霍兹方程或单色标量波的波动方程

\[\triangle u(P,t) - \frac{n^2}{c^2} \frac{\partial^2 u(P,t) }{\partial t^2 } = 0\] 
\[u(P,t) = Re(U(P)\exp(-j2\pi\nu t))\] 

标量波动方程和单色波结合，可以得到
\[Re\{(\triangle + k^2 )U(P)\exp (-j 2\pi\nu t)\} = 0 ,\quad k=2\pi \nu n / c = 2\pi / \lambda\] 

这个等式，是从标量波动方程和单色标量波的数学形式推导出来的， *因此* 表示的是单色标量波的标量波动方程。

#+begin_note
这里是如何推出的？现在想到的解决方法是，有一个隐含的前提假设：\(\forall t \in R\) 都有上述方程成立。
在这个前提下，就只能得到亥姆霍兹方程了。
#+end_note

从这里可以推导出 \((\triangle + k^2)U = 0\) 
这就是亥姆霍兹方程。

* 前提：格林定理（格林第二恒等式）
格林定理是描述空间区域内体积分和边界面积分的某种关系的：
\[\iiint_V(U\triangle G - G\triangle U)dv = \iint_S(U \frac{\partial G}{\partial n} - G \frac{\partial U}{\partial n})ds\] 

* 前提：格林函数
\[G(P_1) = \frac{\exp(jk r_{01})}{r_{01}}\]
这是一个格林函数，是在自由空间边界条件下，标量波动方程在脉冲激发下产生的响应。

* 前提：自由空间格林函数或单位振幅的球面波
从 \(P_0\) 发散出去的单位振幅球面波可以使用下式表示
\[G(P_1) = \frac{\exp(jk r_{01})}{r_{01}}\]
\(P_1\) 就是 \(P_0\) 外任意一点，\(r_{01}\) 是两点连线矢量的长度。

* 推论：亥姆霍兹和基尔霍夫的积分定理
为了使用闭合曲面上的光扰动表示点上的光扰动，我们使用上面的格林定理，利用自由空间格林函数作为辅助函数，可以得到（亥姆霍兹和）基尔霍夫积分定理。
这里使用的格林函数可以理解为对于自由空间脉冲的一种响应。
由于格林定理要求函数必须在积分的空间内连续，所以这里使用的积分体积是外层曲面和内层小球面包围而成的。

最终得出
\[U(P_0) = \frac{1}{4\pi }\int_S \left\{\frac{\partial U}{\partial n}[\frac{\exp(jk r_{01})}{r_{01}}] - U \frac{\partial}{\partial n}[\frac{\exp(jk r_{01})}{r_{01}}]\right\}ds\] 

该定理使得任意一点的场可以用波在包围着一点的任意闭合曲面上的“边值”表示。

* 前提：索末菲辐射条件

* 前提：基尔霍夫边界条件
对于衍射屏平面上的场，遮挡的地方当作没有场，不遮挡的地方当作和没有衍射屏的场一样，这就是基尔霍夫边界条件。
只有满足衍射孔孔径远大于波长的情况下，基尔霍夫边界条件才能满足。
不知道如何证明
直觉上，孔径尺度远大于波长，会让孔径处的衍射效应平均比较少，从而更接近无遮挡情况下的场。

* 推论：菲涅尔-基尔霍夫衍射公式
[[前提：索末菲辐射条件]]
[[前提：基尔霍夫边界条件]]

* 不过，标量衍射理论与微波波谱区的实验符合的很好，只要满足两个条件即可：
1. 衍射孔径比波长大得多
2. 观察点离衍射孔远一些 \(k \gg  \frac{1}{r_{10}}\) 

* 参考
@book{傅里叶光学导论,
  title={傅里叶光学导论},
  author={古德曼 and J.W.)},
  publisher={傅里叶光学导论},
  year={2020},
}
