#+title: 散射截面、微分散射截面、吸收截面、消光截面、雷达截面
#+roam_tags: 随机介质中的波传播与散射
#+roam_alias: 

* 散射截面和一般的截面的概念
- 散射截面 :: 是总散射功率和入射功率通量密度的比。
  \[\sigma_s = P_s / S_i, S_i = |E_i|^2 / (2\eta_0)\] <<poynting>>
  是介质散射能力的一种量度。例如这个比值是1，那么入射功率通量密度有多大，散射功率就多大。
- 一般的截面 :: 某个功率和入射功率通量密度的比值。
比如说

- 吸收截面 :: 总吸收功率和入射功率通量密度的比值 \(\sigma_a = P_a /S_i, P_a = \int_V \frac{1}{2}\omega\varepsilon_0\varepsilon_r''|E|^2dV\)
  如果入射波大小取为1，\(|\vec{E}_i|=1\) ，则根据入射波通量密度[[poynting][展开式]]，上式可以写为
  \[\sigma_a = \int_V k\varepsilon_r''(\bm{r}')|\bm{E}(\bm{r}')|^2dV'\] 
  见石丸15页
- 消光截面（总衰减截面） :: 是总衰减功率和入射功率通量密度的比值。\(\sigma_t = \sigma_a + \sigma_s\)


* 微分散射截面
如果限定成单位立体角的散射截面，那么我们会得到
微分散射截面是*散射截面对空间立体角的导数*。认为散射截面随着空间立体角发生变化。
- 微分散射截面 :: 单位立体角内的散射功率和入射功率通量密度的比。
\[\sigma_d(\hat{o},\hat{i}) = \lim\limits_{R\to \infty }(R^2 S_s) / S_i \] 
数学定义中的 \(R^2 \) 可以理解为散射方向上面积微元和立体角微元的比值，即
\[\frac{R^2 S_s}{S_i} = \frac{S_s dA /d\Omega }{S_i} = \frac{1}{d\Omega } \sigma_s \] 
因此可以将微分散射截面理解为：单位散射方向立体角的散射截面。

另外，微分散射截面等于[[file:20210626142011-散射振幅矢量.org][散射振幅函数]]的模方： \[\sigma_d(\hat{o},\hat{i}) = |\bm{f}(\hat{o},\hat{i})|^2 \] 

* 微分散射截面和散射振幅矢量的关系

* 双站雷达截面和单站雷达截面与微分散射截面的关系
\[\sigma_{bi}(\hat{o},\hat{i}) = 4\pi \sigma_d(\hat{o},\hat{i})\] 
\[\sigma _b = 4\pi \sigma _d(-\hat{i},\hat{i})\] 


* 参考
[[file:20210323105545-激光雷达技术.org][激光雷达技术]] 中使用了散射截面概念。
