#+title: 直接探测的量子极限推导
#+setupfile: src/jake-latex-standard.org
#+OPTIONS: toc:nil
#+roam_tags: 
#+roam_alias: 

对于直接探测，设输入信号光功率为 \(P_S\) ，光电探测器输出的信号电流为 \(i_{s}\)。
\(i_{s}\) 可以表达为
#+name: eqn:signalcurrent
\begin{equation}
i_{s} = \frac{e\eta}{h\nu }P_S = R_i P_S 
\end{equation} 
其中 \(h\nu\) 是光子能量；\(\eta\) 是探测器的量子效率，即单位时间内探测器输出一个电子需要多少光子；\(e\) 是电子电荷量。
\(R_i\) 称为响应度，反映了单位信号光功率造成的信号电流。

光电探测器的输出中包含噪声，可以用各种噪声电流表示。比如
- 背景噪声 \(\overline{i_{nb}^2 }\)，来自探测器对背景光的反应。
- 散粒噪声 \(\overline{i_{ns}^2 }\) ，来自光子的量子效应，因光子的分布存在量子涨落而形成的。
- 暗电流噪声 \(\overline{i_{nd}^2 }\)，来自载流子的产生、复合数的起伏。 
- 热噪声 \(\overline{i_{nT}^2 }\)，来自探测器中的载流子的无规则热运动。

为了了解探测器的极致性能，我们现在分析理想探测器。
假设信号比较强或背景辐射可以忽略，而且探测器内部本身不会产生噪声，那么可以得到一种理想探测器：
- 信号光子限探测器 :: 若探测器内部本身不产生噪声，且背景光辐射可以忽略，那么该探测器是信号光子限探测器。

对这种探测器，除了到达探测器的信号光子涨落引起的噪声（即散粒噪声）以外，其余噪声可以忽略。
该探测器的信噪比，就是探测器信噪比的量子极限。
- 探测器的量子极限 :: 就是对应的信号光子限探测器的信噪比。
  
散粒噪声电流的表达式是：
\[\overline{i_{ns}^2} = 2eR_iP_SB_W\] 
根据式（[[eqn:signalcurrent]]）以及上式可以得到信噪比为
\[\mathrm{SNR_{QL-D}} = i_s^2 / \overline{i_{ns}^2} = \frac{\eta P_S}{2h\nu B_W}\] 
这里的 \(\mathrm{SNR_{QL-D}}\) 表示直接探测（Direct Detection）情况下的量子极限（Quantum Limit）。
